[package]
org = "asus"
name = "ballerina_backend"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mysql"
version = "3.4.0"

[platform]
target = "java8"

[[platform.libraries]]
artifactId = "mysql-connector-j"
version = "9.4.0"
path = "./libs/mysql-connector-j-9.4.0.jar"
groupId = "mysql"

