[package]
org = "asus"
name = "ballerina_backend"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true



[[platform.java17.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.0.33"

